version: "3.9"
services:
  py3-abc:
    build:
      context: ./py3
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/workspace
    expose:
      - "8888"
    # 下記の左の番号だけを変更する
    ports:
      - "7004:8888"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ../workspace:/workspace

    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu